import { useState, useEffect } from "react";
import { ArrowLeft, FileDown, Loader2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { jsPDF } from "jspdf";
import { useChatStore } from "../store/useChatStore";
import axiosInstance from "../lib/axios";
import { saveBinaryFile } from "../lib/download";
import toast from "react-hot-toast";

const ExportPdfPage = () => {
  const navigate = useNavigate();
  const selectedUser = useChatStore((s) => s.selectedUser);
  const [loading, setLoading] = useState(false);
  const [fetching, setFetching] = useState(true);
  const [exportData, setExportData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!selectedUser?._id) {
      navigate("/settings", { replace: true });
      return;
    }
    let cancelled = false;
    (async () => {
      try {
        const res = await axiosInstance.get(`/messages/export/${selectedUser._id}`);
        if (!cancelled) setExportData(res.data);
      } catch (err) {
        if (!cancelled) setError(err?.response?.data?.message || "Failed to load chat data");
      } finally {
        if (!cancelled) setFetching(false);
      }
    })();
    return () => { cancelled = true; };
  }, [selectedUser?._id, navigate]);

  const formatDate = (iso) => {
    const d = new Date(iso);
    return d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
  };

  const formatTime = (iso) => {
    const d = new Date(iso);
    return d.toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" });
  };

  const buildPdf = () => {
    if (!exportData) return;
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 15;
    const maxTextW = pageW - margin * 2;
    let y = 20;

    // Header
    doc.setFontSize(18);
    doc.setTextColor(30, 30, 30);
    doc.text(selectedUser.fullName || "Chat Export", margin, y);
    y += 8;

    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Exported ${formatDate(exportData.exportedAt)}  ·  ${exportData.messageCount} messages`,
      margin,
      y
    );
    y += 4;

    if (exportData.participants?.length) {
      const names = exportData.participants.map((p) => p.name).join(", ");
      doc.text(`Participants: ${names}`, margin, y);
    }
    y += 10;

    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageW - margin, y);
    y += 8;

    // Messages
    const messages = exportData.messages || [];
    for (const msg of messages) {
      // Check for page break (leave room for a message block)
      if (y > 265) {
        doc.addPage();
        y = 20;
      }

      // Sender + time
      doc.setFontSize(9);
      doc.setTextColor(50, 50, 50);
      doc.setFont(undefined, "bold");
      doc.text(String(msg.from || "Unknown"), margin, y);
      doc.setFont(undefined, "normal");
      doc.setTextColor(140, 140, 140);
      doc.text(formatTime(msg.at), margin + doc.getTextWidth(String(msg.from || "Unknown")) + 4, y);
      y += 5;

      // Text
      if (msg.text) {
        doc.setFontSize(10);
        doc.setTextColor(40, 40, 40);
        const clean = String(msg.text).replace(/<[^>]*>/g, "").trim();
        if (clean) {
          const lines = doc.splitTextToSize(clean, maxTextW);
          for (const line of lines) {
            if (y > 275) { doc.addPage(); y = 20; }
            doc.text(line, margin, y);
            y += 4.5;
          }
        }
      }

      // Media
      if (msg.media?.length) {
        doc.setFontSize(9);
        doc.setTextColor(100, 100, 100);
        for (const url of msg.media) {
          if (y > 275) { doc.addPage(); y = 20; }
          let label = "[Attachment]";
          if (typeof url === "string") {
            if (/\.(mp4|mov|avi|webm)/i.test(url)) label = "[Video]";
            else if (/\.(mp3|wav|ogg|opus|m4a|aac)/i.test(url)) label = "[Voice Note]";
            else if (/\.(jpg|jpeg|png|gif|webp|svg)/i.test(url)) label = "[Photo]";
          }
          doc.text(label, margin + 4, y);
          y += 4.5;
        }
      }

      // Call
      if (msg.call) {
        doc.setFontSize(9);
        doc.setTextColor(100, 100, 100);
        const dur = msg.call.duration;
        const durStr = dur ? `${Math.floor(dur / 60)}m ${dur % 60}s` : "";
        const type = msg.call.type || msg.call.callType || "voice";
        doc.text(`[${type === "video" ? "Video" : "Voice"} call${durStr ? " · " + durStr : ""}]`, margin + 4, y);
        y += 4.5;
      }

      // Date separator between different days
      y += 2;
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(170, 170, 170);
    const footerText = `Generated by Chatty · ${new Date().toLocaleDateString()}`;
    doc.text(footerText, margin, doc.internal.pageSize.getHeight() - 10);

    return doc;
  };

  const handleExport = async () => {
    setLoading(true);
    try {
      const doc = buildPdf();
      if (!doc) return;
      const dataUri = doc.output("datauristring");
      const base64 = dataUri.substring(dataUri.indexOf(",") + 1);
      const safeName = (selectedUser.fullName || "chat").replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 40);
      const dateStr = new Date().toISOString().slice(0, 10);
      const fileName = `chat-${safeName}-${dateStr}.pdf`;
      await saveBinaryFile(fileName, base64, "application/pdf");
      toast.success("PDF exported successfully");
    } catch (err) {
      console.error("PDF export error:", err);
      toast.error("Failed to export PDF");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      className="container min-h-screen max-w-3xl px-4 pt-20 pb-12 mx-auto"
      style={{ backgroundColor: "var(--color-base-100)", color: "var(--color-neutral)" }}
    >
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate("/settings")}
            className="p-2 rounded-full transition-colors hover:bg-base-200"
            title="Back to settings"
          >
            <ArrowLeft size={18} />
          </button>
          <div className="flex items-center gap-2">
            <div className="grid rounded-full place-items-center size-10 bg-primary/10">
              <FileDown size={20} className="text-primary" />
            </div>
            <div>
              <h1 className="text-lg font-semibold leading-tight">Export Chat as PDF</h1>
              <p className="text-xs opacity-60">
                {selectedUser?.fullName
                  ? `Export conversation with ${selectedUser.fullName}`
                  : "Save a conversation to a styled PDF file"}
              </p>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="space-y-4">
          {fetching && (
            <div className="flex items-center justify-center py-16">
              <Loader2 size={24} className="animate-spin text-primary" />
            </div>
          )}

          {!fetching && error && (
            <div className="text-center py-16 space-y-3">
              <p className="text-sm opacity-70">{error}</p>
              <button
                onClick={() => navigate("/settings")}
                className="btn btn-sm btn-ghost"
              >
                Go back
              </button>
            </div>
          )}

          {!fetching && !error && exportData && (
            <>
              {/* Summary card */}
              <div className="overflow-hidden rounded-2xl p-4 space-y-3"
                   style={{ backgroundColor: "var(--color-base-200)" }}>
                <div className="flex items-center justify-between text-sm">
                  <span className="opacity-60">Messages</span>
                  <span className="font-medium">{exportData.messageCount}</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="opacity-60">Participants</span>
                  <span className="font-medium">{exportData.participants?.length || 0}</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="opacity-60">Exported at</span>
                  <span className="font-medium">{formatDate(exportData.exportedAt)}</span>
                </div>
              </div>

              {/* Export button */}
              <button
                onClick={handleExport}
                disabled={loading}
                className="btn btn-primary w-full gap-2"
              >
                {loading ? (
                  <Loader2 size={16} className="animate-spin" />
                ) : (
                  <FileDown size={16} />
                )}
                {loading ? "Generating PDF…" : "Export as PDF"}
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default ExportPdfPage;
